##############################################################################
# +------------------------------------------------------------------------+ #
# |                              Levelo Config                             | #
# |                 https://github.com/ProfiiQus/Levelo                    | #
# +------------------------------------------------------------------------+ #
##############################################################################

storage: "mysql"